# Whether to enable auto update
auto-update: true

# Print debug messages in console.
debug: false

# Language mappings
# Format: <provided language code>: <slimefun language code>
language-mappings:
  en-US: en
