name: SlimefunTranslation
version: '${project.version}'
main: net.guizhanss.slimefuntranslation.SlimefunTranslation
api-version: 1.16
depend:
  - Slimefun
  - ProtocolLib
  - PlaceholderAPI
softdepend:
  - GuizhanLibPlugin
authors: [ ybw0014 ]
description: A Slimefun Addon that translates items without actually modifying the items.
commands:
  sftranslation:
    description: SlimefunTranslation Command
    usage: /<command> <subcommand>
    aliases: [ slimefuntranslation, sft, sftr, sftransl ]

permissions:
  sftranslation.command.id:
    description: Get the ID of the Slimefun item in your main hand
    default: true
  sftranslation.command.search:
    description: Search for a Slimefun item with your current language
    default: true
  sftranslation.command.translation:
    description: Manage the translation files
    default: op
