name: Blob Build

on:
  push:
    branches:
      - master

jobs:
  build:
    if: startsWith(github.event.head_commit.message, '[CI skip]') == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build shadowJar

      - name: Rename jar file
        run: mv build/libs/SlimefunTranslation-*.jar build/libs/SlimefunTranslation.jar

      - name: Upload to Blob Builds
        uses: WalshyDev/blob-builds/gh-action@main
        with:
          project: SlimefunTranslation
          file: ./build/libs/SlimefunTranslation.jar
          apiToken: ${{ secrets.BLOB_BUILDS_API_TOKEN }}
          releaseNotes: ${{ github.event.head_commit.message }}
